--[[
    Robotron AI Lua script for MAME.

    Current scope:
      - Sends a 315-value state vector:
        core stats + ELIST bytes + active OBPTR/HPTR/RPTR/PPTR list features
      - Receives dual 8-way joystick commands: movement_dir, firing_dir
--]]

local RAW_SOCKET_ADDRESS = os.getenv("ROBOTRON_SOCKET_ADDRESS") or "127.0.0.1:9999"
local SOCKET_ADDRESS = RAW_SOCKET_ADDRESS
if string.sub(SOCKET_ADDRESS, 1, 7) ~= "socket." then
    SOCKET_ADDRESS = "socket." .. SOCKET_ADDRESS
end
local SOCKET_READ_TIMEOUT_S = 3.5
local CONNECTION_RETRY_INTERVAL_S = 1.0
local SAVE_INTERVAL_S = 300
local unpack = table.unpack or unpack

-- Startup diagnostics (bounded, opt-in style flags kept local to script).
local DEBUG_STARTUP_TRACE = false
local DEBUG_TRACE_FRAMES = 10
local DEBUG_BYPASS_SOCKET_FOR_FRAMES = 0
local DEBUG_TRACE_FILE = "logs/startup_trace.log"
local DEBUG_FORCE_ACTION_FRAMES = 0
local DEBUG_FORCE_MOVE_DIR = 2  -- right
local DEBUG_FORCE_FIRE_DIR = 2  -- right
local DEATH_PENALTY_POINTS = 1000

local mainCpu = nil
local mem = nil
local controls = nil

local current_socket = nil
local last_connection_attempt_time = 0
local shutdown_requested = false

local frame_counter = 0
local last_save_time = 0
local previous_player_alive = 1
local previous_score = 0

-- Autoboot input sequence (MAME input level, no game-specific memory logic required).
-- Every cycle: pulse Coin 1, then pulse 1P Start shortly after.
local AUTOBOOT_ENABLED = true
local AUTOBOOT_CYCLE_FRAMES = 300
local AUTOBOOT_COIN_PULSE_FRAMES = 3
local AUTOBOOT_START_DELAY_FRAMES = 18
local AUTOBOOT_START_PULSE_FRAMES = 3

-- Robotron RAM symbols (from Williams map):
-- STATUS = 0x9859
-- In PLAYRV, bit0 gates player control update; on player death PLEND sets STATUS to 0x1B.
local STATUS_ADDR = 0x9859
local STATUS_PLAYER_INACTIVE_MASK = 0x01

-- Player PLDATA symbols (from Williams map generated by lwasm):
--   ZP1SCR = 0xBDE4 (4 bytes packed BCD, MSB first)
--   ZP1RP  = 0xBDE8 (4 bytes packed BCD, MSB first)
--   ZP1LAS = 0xBDEC (1 byte)
--   ZP1WAV = 0xBDED (1 byte)
--   ZP1ENM = 0xBDEE (50 bytes; first 22 mirror ELIST fields, rest reserved)
local ZP1SCR_ADDR = 0xBDE4
local ZP1RP_ADDR = 0xBDE8
local ZP1LAS_ADDR = 0xBDEC
local ZP1WAV_ADDR = 0xBDED
local ZP1ENM_ADDR = 0xBDEE
local ZP1ENM_SIZE = 50

-- Active object-list heads (from Williams base-page RAM map).
local OBPTR_ADDR = 0x9819 -- obstacle list
local HPTR_ADDR = 0x981B  -- humans to rescue
local RPTR_ADDR = 0x9821  -- robots/enemies
local PPTR_ADDR = 0x9823  -- fatal obstacles

-- Object pool geometry (master list @ OLIST).
local OLIST_START = 0x9900
local OLIST_ENTRY_SIZE = 0x18
local OLIST_CAPACITY = 180
local OLIST_END = OLIST_START + (OLIST_ENTRY_SIZE * OLIST_CAPACITY)

-- Object entry offsets.
local OLINK_OFF = 0x00
local OPICT_OFF = 0x02
local OBJX_OFF = 0x04
local OBJY_OFF = 0x05
local OX16_OFF = 0x0A
local OY16_OFF = 0x0C

-- Fixed-size state encoding for linked lists (stable for learning).
local LIST_SLOT_COUNT = 16
local LIST_FEATURES_PER_SLOT = 4 -- present, x, y, type_ptr_norm
local MAX_LIST_WALK = 256

local ACTIVE_LISTS = {
    {name = "obptr", addr = OBPTR_ADDR},
    {name = "hptr", addr = HPTR_ADDR},
    {name = "rptr", addr = RPTR_ADDR},
    {name = "pptr", addr = PPTR_ADDR},
}

local EXPECTED_LIST_FEATURES_PER_LIST = 1 + (LIST_SLOT_COUNT * LIST_FEATURES_PER_SLOT)
local EXPECTED_STATE_VALUES = 5 + ZP1ENM_SIZE + (#ACTIVE_LISTS * EXPECTED_LIST_FEATURES_PER_LIST)
local CANONICAL_TYPE_BACKTRACK_STEPS = 8

-- Cache canonicalized descriptor pointers to avoid repeated probe reads.
local canonical_type_cache = {}

local function trace_enabled_for_frame(frame_idx)
    if not DEBUG_STARTUP_TRACE then
        return false
    end
    if frame_idx == nil then
        return false
    end
    return frame_idx < DEBUG_TRACE_FRAMES
end

local function trace_log(frame_idx, phase, detail, force)
    if not DEBUG_STARTUP_TRACE then
        return
    end
    local enabled = force or trace_enabled_for_frame(frame_idx)
    if not enabled then
        return
    end
    local ts = os.date("%Y-%m-%d %H:%M:%S")
    local frame_text = (frame_idx == nil) and "-" or tostring(frame_idx)
    local line = string.format("[trace %s] frame=%s phase=%s %s", ts, frame_text, tostring(phase), tostring(detail or ""))
    print(line)

    local fh = io.open(DEBUG_TRACE_FILE, "a")
    if fh then
        fh:write(line .. "\n")
        fh:close()
    end
end

local function read_player_alive(memory)
    local status = memory:read_u8(STATUS_ADDR)
    if (status & STATUS_PLAYER_INACTIVE_MASK) ~= 0 then
        return 0
    end
    return 1
end

local function decode_bcd4(memory, addr)
    local value = 0
    for i = 0, 3 do
        local byte = memory:read_u8(addr + i)
        local hi = (byte >> 4) & 0x0F
        local lo = byte & 0x0F
        -- Treat non-BCD digits as invalid instead of clamping to 9,
        -- which can fabricate very large scores from transient RAM.
        if hi > 9 or lo > 9 then
            return nil
        end
        value = (value * 10) + hi
        value = (value * 10) + lo
    end
    return value
end

local function read_player_score(memory)
    return decode_bcd4(memory, ZP1SCR_ADDR)
end

local function read_next_replay_level(memory)
    return decode_bcd4(memory, ZP1RP_ADDR)
end

local function read_num_lasers(memory)
    return memory:read_u8(ZP1LAS_ADDR)
end

local function read_wave_number(memory)
    return memory:read_u8(ZP1WAV_ADDR)
end

local function read_enemy_state(memory)
    local raw = {}
    for i = 0, ZP1ENM_SIZE - 1 do
        raw[i + 1] = memory:read_u8(ZP1ENM_ADDR + i)
    end

    -- ELIST mirror (first 22 bytes) in order from RRF.ASM.
    local enemy_state = {
        raw = raw,
        robspd = raw[1], rmxspd = raw[2], enfnum = raw[3], enstim = raw[4],
        cdptim = raw[5], hlkspd = raw[6], bshtim = raw[7], brnspd = raw[8],
        tnksht = raw[9], shlspd = raw[10], tdptim = raw[11], sqspd = raw[12],
        robcnt = raw[13], pstcnt = raw[14], momcnt = raw[15], dadcnt = raw[16],
        kidcnt = raw[17], hlkcnt = raw[18], brncnt = raw[19], circnt = raw[20],
        sqcnt = raw[21], tnkcnt = raw[22],
    }

    return enemy_state
end

local function read_u16_be(memory, addr)
    local hi = memory:read_u8(addr)
    local lo = memory:read_u8(addr + 1)
    return ((hi << 8) | lo) & 0xFFFF
end

local function u16_to_i16(v)
    local u = v & 0xFFFF
    if u >= 0x8000 then
        return u - 0x10000
    end
    return u
end

local function norm_i16(v)
    local x = math.max(-32768, math.min(32767, v or 0))
    return (x + 32768) / 65535.0
end

local function is_probable_object_descriptor(memory, addr)
    if addr == nil then
        return false
    end
    local a = addr & 0xFFFF
    if a > 0xFFFB then
        return false
    end

    local base_pic_ptr = read_u16_be(memory, a)
    local image_count = memory:read_u8(a + 2)
    local bytes_per = memory:read_u8(a + 3)

    if base_pic_ptr == 0 then
        return false
    end
    if image_count < 1 or image_count > 64 then
        return false
    end
    -- Robotron object descriptors are predominantly 4-byte entries; tanks use 6.
    if bytes_per ~= 4 and bytes_per ~= 6 then
        return false
    end
    return true
end

local function canonicalize_object_type_ptr(memory, pict_ptr)
    local p = (pict_ptr or 0) & 0xFFFF
    if p == 0 then
        return 0
    end

    local cached = canonical_type_cache[p]
    if cached ~= nil then
        return cached
    end

    -- First try exact pointer; if animated frame pointers are in use, walk backward
    -- in 4-byte steps to find the stable descriptor header.
    if is_probable_object_descriptor(memory, p) then
        canonical_type_cache[p] = p
        return p
    end
    for i = 1, CANONICAL_TYPE_BACKTRACK_STEPS do
        local cand = (p - (i * 4)) & 0xFFFF
        if is_probable_object_descriptor(memory, cand) then
            canonical_type_cache[p] = cand
            return cand
        end
    end

    -- Fallback: 4-byte alignment still removes some frame-pointer jitter.
    local aligned = p & 0xFFFC
    canonical_type_cache[p] = aligned
    return aligned
end

local function is_valid_object_ptr(ptr)
    if ptr == nil or ptr == 0 then
        return false
    end
    if ptr < OLIST_START or ptr >= OLIST_END then
        return false
    end
    return ((ptr - OLIST_START) % OLIST_ENTRY_SIZE) == 0
end

local function extract_list_state(memory, head_addr)
    local objects = {}
    local seen = {}
    local ptr = read_u16_be(memory, head_addr)
    local steps = 0

    while ptr ~= 0 and steps < MAX_LIST_WALK do
        if seen[ptr] then
            break
        end
        seen[ptr] = true
        steps = steps + 1

        if not is_valid_object_ptr(ptr) then
            break
        end

        local pict_ptr = read_u16_be(memory, ptr + OPICT_OFF)
        local canonical_type_ptr = canonicalize_object_type_ptr(memory, pict_ptr)
        local x16 = u16_to_i16(read_u16_be(memory, ptr + OX16_OFF))
        local y16 = u16_to_i16(read_u16_be(memory, ptr + OY16_OFF))
        local objx = memory:read_u8(ptr + OBJX_OFF)
        local objy = memory:read_u8(ptr + OBJY_OFF)
        objects[#objects + 1] = {
            obj_addr = ptr,
            pict_ptr = pict_ptr,
            canonical_type_ptr = canonical_type_ptr,
            x16 = x16,
            y16 = y16,
            objx = objx,
            objy = objy,
        }

        ptr = read_u16_be(memory, ptr + OLINK_OFF)
    end

    table.sort(objects, function(a, b)
        return a.obj_addr < b.obj_addr
    end)

    local features = {}
    features[#features + 1] = math.min(1.0, (#objects / LIST_SLOT_COUNT))

    for i = 1, LIST_SLOT_COUNT do
        local obj = objects[i]
        if obj then
            features[#features + 1] = 1.0
            -- Use true 16-bit world coordinates from OX16/OY16 (RRF.ASM).
            features[#features + 1] = norm_i16(obj.x16)
            features[#features + 1] = norm_i16(obj.y16)
            -- Canonical object-type signal anchored to descriptor base, not raw frame pointer.
            features[#features + 1] = (obj.canonical_type_ptr or 0) / 65535.0
        else
            features[#features + 1] = 0.0
            features[#features + 1] = 0.0
            features[#features + 1] = 0.0
            features[#features + 1] = 0.0
        end
    end

    return features, #objects
end

local function initialize_mame_interface()
    local success, err = pcall(function()
        if not manager or not manager.machine then
            error("MAME manager.machine not available")
        end
        mainCpu = manager.machine.devices[":maincpu"]
        if not mainCpu then
            error("Main CPU not found")
        end
        mem = mainCpu.spaces["program"]
        if not mem then
            error("Program memory space not found")
        end
    end)

    if not success then
        print("Error accessing MAME interface: " .. tostring(err))
        return false
    end

    print("MAME interface initialized.")
    return true
end

local function close_socket()
    if current_socket then
        current_socket:close()
        current_socket = nil
    end
end

local function open_socket()
    close_socket()

    local open_result = nil
    local ok, err = pcall(function()
        local sock = emu.file("rw")
        local result = sock:open(SOCKET_ADDRESS)
        if result == nil then
            -- Required 2-byte handshake.
            sock:write(string.pack(">H", 0))
            current_socket = sock
        else
            open_result = tostring(result)
            sock:close()
        end
    end)

    if not ok or not current_socket then
        local reason = tostring(err or open_result or "unknown error")
        trace_log(nil, "socket_open_failed", "addr=" .. SOCKET_ADDRESS .. " reason=" .. reason, true)
        print("Socket open failed: " .. SOCKET_ADDRESS .. " (" .. reason .. ")")
        close_socket()
        return false
    end

    trace_log(nil, "socket_open_ok", "addr=" .. SOCKET_ADDRESS, true)
    print("Socket connection opened to " .. SOCKET_ADDRESS)
    return true
end

local function find_field(ioport, field_name_options)
    local candidate_ports = {
        ":IN0", ":IN1", ":IN2", ":IN3", ":IN4", ":IN5",
        ":P1", ":P1JOY", ":P1BUTTONS", ":JOYSTICK1", ":JOYSTICK2", ":BUTTONSP1"
    }

    for _, port_name in ipairs(candidate_ports) do
        local port = ioport.ports[port_name]
        if port then
            for _, field_name in ipairs(field_name_options) do
                local field = port.fields[field_name]
                if field then
                    return field, field_name
                end
            end
        end
    end

    return nil, nil
end

local function find_field_fuzzy(ioport, name_fragments)
    local function any_match(label)
        local ll = string.lower(label or "")
        for _, frag in ipairs(name_fragments) do
            local ff = string.lower(frag)
            if string.find(ll, ff, 1, true) then
                return true
            end
        end
        return false
    end

    local candidate_ports = {":IN0", ":IN1", ":IN2", ":IN3", ":IN4", ":IN5", ":P1", ":P2"}
    for _, port_name in ipairs(candidate_ports) do
        local port = ioport.ports[port_name]
        if port and port.fields then
            for label, field in pairs(port.fields) do
                if any_match(label) then
                    return field, label
                end
            end
        end
    end

    for _, port in pairs(ioport.ports) do
        if port and port.fields then
            for label, field in pairs(port.fields) do
                if any_match(label) then
                    return field, label
                end
            end
        end
    end

    return nil, nil
end

local function bind_control(ioport, exact_names, fuzzy_names, tag)
    local field, label = find_field(ioport, exact_names)
    if field then
        print(string.format("Mapped %-10s => %s", tag, tostring(label)))
        return field
    end
    field, label = find_field_fuzzy(ioport, fuzzy_names)
    if field then
        print(string.format("Mapped %-10s => %s (fuzzy)", tag, tostring(label)))
        return field
    end
    print(string.format("WARN: unmapped control %-10s", tag))
    return nil
end

local Controls = {}
Controls.__index = Controls

function Controls:new(mame_manager)
    local self = setmetatable({}, Controls)
    local ioport = mame_manager.machine.ioport

    self.move_up = bind_control(
        ioport,
        {"P1 Move Up", "P1 Left Up", "P1 Joystick Up"},
        {"move up", "left up", "left stick up", "joystick up"},
        "move_up"
    )
    self.move_down = bind_control(
        ioport,
        {"P1 Move Down", "P1 Left Down", "P1 Joystick Down"},
        {"move down", "left down", "left stick down", "joystick down"},
        "move_down"
    )
    self.move_left = bind_control(
        ioport,
        {"P1 Move Left", "P1 Left Left", "P1 Joystick Left"},
        {"move left", "left left", "left stick left", "joystick left"},
        "move_left"
    )
    self.move_right = bind_control(
        ioport,
        {"P1 Move Right", "P1 Left Right", "P1 Joystick Right"},
        {"move right", "left right", "left stick right", "joystick right"},
        "move_right"
    )

    self.fire_up = bind_control(
        ioport,
        {"P1 Fire Up", "P1 Right Up"},
        {"fire up", "right up", "right stick up"},
        "fire_up"
    )
    self.fire_down = bind_control(
        ioport,
        {"P1 Fire Down", "P1 Right Down"},
        {"fire down", "right down", "right stick down"},
        "fire_down"
    )
    self.fire_left = bind_control(
        ioport,
        {"P1 Fire Left", "P1 Right Left"},
        {"fire left", "right left", "right stick left"},
        "fire_left"
    )
    self.fire_right = bind_control(
        ioport,
        {"P1 Fire Right", "P1 Right Right"},
        {"fire right", "right right", "right stick right"},
        "fire_right"
    )

    self.p1_start = bind_control(
        ioport,
        {"1 Player Start", "P1 Start", "Start 1"},
        {"1 player start", "start 1", "p1 start"},
        "start"
    )
    self.coin_1 = bind_control(
        ioport,
        {"Coin 1", "P1 Coin", "Insert Coin"},
        {"coin 1", "insert coin"},
        "coin_1"
    )

    return self
end

local DIR_AXES = {
    [0] = {1, 0, 0, 0}, -- up
    [1] = {1, 0, 0, 1}, -- up-right
    [2] = {0, 0, 0, 1}, -- right
    [3] = {0, 1, 0, 1}, -- down-right
    [4] = {0, 1, 0, 0}, -- down
    [5] = {0, 1, 1, 0}, -- down-left
    [6] = {0, 0, 1, 0}, -- left
    [7] = {1, 0, 1, 0}, -- up-left
}

local function apply_direction(up_field, down_field, left_field, right_field, dir_idx)
    local axis = DIR_AXES[math.max(0, math.min(7, dir_idx or 0))] or DIR_AXES[0]

    if up_field then up_field:set_value(axis[1]) end
    if down_field then down_field:set_value(axis[2]) end
    if left_field then left_field:set_value(axis[3]) end
    if right_field then right_field:set_value(axis[4]) end
end

function Controls:apply_action(move_dir, fire_dir, start_cmd, coin_cmd)
    apply_direction(self.move_up, self.move_down, self.move_left, self.move_right, move_dir)
    apply_direction(self.fire_up, self.fire_down, self.fire_left, self.fire_right, fire_dir)

    if self.p1_start then
        self.p1_start:set_value(start_cmd)
    end
    if self.coin_1 then
        self.coin_1:set_value(coin_cmd)
    end
end

local function serialize_frame(player_alive, score, replay_level, num_lasers, wave_number, enemy_state, list_state_values,
                               done, subj_reward, obj_reward, save_signal)
    local score_u32 = math.max(0, math.min(4294967295, math.floor(score or 0)))
    local replay_u32 = math.max(0, math.min(4294967295, math.floor(replay_level or 0)))
    local lasers_u8 = math.max(0, math.min(255, math.floor(num_lasers or 0)))
    local wave_u8 = math.max(0, math.min(255, math.floor(wave_number or 0)))

    local state_values = {}
    state_values[#state_values + 1] = ((player_alive or 0) ~= 0) and 1.0 or 0.0
    state_values[#state_values + 1] = score_u32 / 99999999.0
    state_values[#state_values + 1] = replay_u32 / 99999999.0
    state_values[#state_values + 1] = lasers_u8 / 9.0
    state_values[#state_values + 1] = wave_u8 / 255.0
    for i = 1, ZP1ENM_SIZE do
        state_values[#state_values + 1] = (enemy_state.raw[i] or 0) / 255.0
    end
    for i = 1, #list_state_values do
        state_values[#state_values + 1] = list_state_values[i]
    end
    local num_values = #state_values
    if num_values ~= EXPECTED_STATE_VALUES then
        error(string.format("state size mismatch: got=%d expected=%d", num_values, EXPECTED_STATE_VALUES))
    end

    local header = string.pack(
        ">HddBIBBIBB",
        num_values,
        subj_reward,
        obj_reward,
        done and 1 or 0,
        score_u32,
        player_alive,
        save_signal,
        replay_u32,
        lasers_u8,
        wave_u8
    )

    local state_payload_parts = {}
    for i = 1, num_values do
        state_payload_parts[#state_payload_parts + 1] = string.pack(">f", state_values[i])
    end
    local state_payload = table.concat(state_payload_parts)
    return header .. state_payload
end

local function process_frame_via_socket(frame_payload, frame_idx)
    if not current_socket then
        trace_log(frame_idx, "socket_open_needed", "no active socket")
        if not open_socket() then
            trace_log(frame_idx, "socket_open_failed", "open_socket() returned false")
            return 0, 0, false
        end
        trace_log(frame_idx, "socket_open_ok", "socket ready")
    end

    local write_ok, write_err = pcall(function()
        trace_log(frame_idx, "socket_write_begin", "payload_bytes=" .. tostring(#frame_payload))
        local length_header = string.pack(">H", #frame_payload)
        current_socket:write(length_header .. frame_payload)
    end)

    if not write_ok then
        trace_log(frame_idx, "socket_write_error", tostring(write_err))
        print("Socket write error: " .. tostring(write_err))
        close_socket()
        return 0, 0, false
    end
    trace_log(frame_idx, "socket_write_ok", "payload sent")

    local read_ok, read_result = pcall(function()
        trace_log(frame_idx, "socket_read_begin", "waiting for 2-byte action")
        local started = os.clock()
        while (os.clock() - started) < SOCKET_READ_TIMEOUT_S do
            local action_bytes = current_socket:read(2)
            if action_bytes and #action_bytes == 2 then
                local move_dir, fire_dir = string.unpack("bb", action_bytes)
                trace_log(frame_idx, "socket_read_ok", string.format("move=%d fire=%d", move_dir, fire_dir))
                return {move_dir, fire_dir}
            end
        end
        trace_log(frame_idx, "socket_read_timeout", "using neutral action")
        return {0, 0}
    end)

    if not read_ok then
        trace_log(frame_idx, "socket_read_error", tostring(read_result))
        print("Socket read error: " .. tostring(read_result))
        close_socket()
        return 0, 0, false
    end

    local move_dir, fire_dir = unpack(read_result)
    return move_dir or 0, fire_dir or 0, true
end

local function determine_meta_commands(frame_idx, player_alive)
    local start_cmd = 0
    local coin_cmd = 0

    -- Keep autoboot inputs out of active gameplay to avoid contaminating control/reward dynamics.
    if AUTOBOOT_ENABLED and (player_alive == 0) then
        local cycle_pos = frame_idx % AUTOBOOT_CYCLE_FRAMES
        if cycle_pos < AUTOBOOT_COIN_PULSE_FRAMES then
            coin_cmd = 1
        end
        if cycle_pos >= AUTOBOOT_START_DELAY_FRAMES and
           cycle_pos < (AUTOBOOT_START_DELAY_FRAMES + AUTOBOOT_START_PULSE_FRAMES) then
            start_cmd = 1
        end
    end

    return start_cmd, coin_cmd
end

local function frame_callback()
    if not mem or not controls then
        return true
    end

    trace_log(frame_counter, "frame_begin", "callback entered")

    local ok_alive, alive_or_err = pcall(read_player_alive, mem)
    if not ok_alive then
        trace_log(frame_counter, "read_player_alive_error", tostring(alive_or_err), true)
        return true
    end
    local player_alive = (alive_or_err ~= 0) and 1 or 0
    trace_log(frame_counter, "read_player_alive", "alive=" .. tostring(player_alive))

    local ok_core, score, replay_level, num_lasers, wave_number = pcall(function()
        local score = math.max(0, math.floor(read_player_score(mem) or 0))
        local replay_level = math.max(0, math.floor(read_next_replay_level(mem) or 0))
        local num_lasers = math.max(0, math.floor(read_num_lasers(mem) or 0))
        local wave_number = math.max(0, math.floor(read_wave_number(mem) or 0))
        return score, replay_level, num_lasers, wave_number
    end)
    if not ok_core then
        trace_log(frame_counter, "read_core_stats_error", tostring(score), true)
        return true
    end
    trace_log(
        frame_counter,
        "read_core_stats",
        string.format("score=%d replay=%d lasers=%d wave=%d", score, replay_level, num_lasers, wave_number)
    )

    local ok_enemy, enemy_or_err = pcall(read_enemy_state, mem)
    if not ok_enemy then
        trace_log(frame_counter, "read_enemy_state_error", tostring(enemy_or_err), true)
        return true
    end
    local enemy_state = enemy_or_err
    trace_log(frame_counter, "read_enemy_state", "bytes=" .. tostring(#enemy_state.raw))

    local list_state_values = {}
    local list_counts = {}
    for _, def in ipairs(ACTIVE_LISTS) do
        local ok_list, vals_or_err, count = pcall(extract_list_state, mem, def.addr)
        if not ok_list then
            trace_log(frame_counter, "read_list_state_error", def.name .. ": " .. tostring(vals_or_err), true)
            return true
        end
        for i = 1, #vals_or_err do
            list_state_values[#list_state_values + 1] = vals_or_err[i]
        end
        list_counts[#list_counts + 1] = string.format("%s=%d", def.name, count or 0)
    end
    trace_log(frame_counter, "read_active_lists", table.concat(list_counts, " "))

    local done = (previous_player_alive == 1 and player_alive == 0)
    local score_delta = score - previous_score
    if score_delta < 0 then
        score_delta = 0
    end
    local obj_reward = score_delta
    if done then
        obj_reward = obj_reward - DEATH_PENALTY_POINTS
    end
    local subj_reward = 0.0
    trace_log(
        frame_counter,
        "reward_calc",
        string.format("score_delta=%d done=%s death_penalty=%d obj_reward=%.1f",
            score_delta, tostring(done), done and DEATH_PENALTY_POINTS or 0, obj_reward)
    )

    local now = os.time()
    local save_signal = 0
    if shutdown_requested or (now - last_save_time) >= SAVE_INTERVAL_S then
        save_signal = 1
        last_save_time = now
    end

    local ok_payload, payload_or_err = pcall(
        serialize_frame,
        player_alive, score, replay_level, num_lasers, wave_number, enemy_state, list_state_values,
        done, subj_reward, obj_reward, save_signal
    )
    if not ok_payload then
        trace_log(frame_counter, "serialize_frame_error", tostring(payload_or_err), true)
        return true
    end
    local payload = payload_or_err
    local payload_count = 5 + ZP1ENM_SIZE + #list_state_values
    trace_log(frame_counter, "serialize_frame", "num_values=" .. tostring(payload_count) .. " bytes=" .. tostring(#payload))

    local move_cmd, fire_cmd = 0, 0
    local socket_ok = false
    if DEBUG_BYPASS_SOCKET_FOR_FRAMES > 0 and frame_counter < DEBUG_BYPASS_SOCKET_FOR_FRAMES then
        trace_log(frame_counter, "socket_bypass", "bypassing exchange; neutral action")
        move_cmd, fire_cmd, socket_ok = 0, 0, true
    elseif current_socket then
        move_cmd, fire_cmd, socket_ok = process_frame_via_socket(payload, frame_counter)
    else
        if (now - last_connection_attempt_time) >= CONNECTION_RETRY_INTERVAL_S then
            trace_log(frame_counter, "socket_retry", "attempting reconnect")
            last_connection_attempt_time = now
            open_socket()
        end
        move_cmd, fire_cmd = 0, 0
    end

    if not socket_ok then
        move_cmd, fire_cmd = 0, 0
    end

    if DEBUG_FORCE_ACTION_FRAMES > 0 and frame_counter < DEBUG_FORCE_ACTION_FRAMES then
        move_cmd = DEBUG_FORCE_MOVE_DIR
        fire_cmd = DEBUG_FORCE_FIRE_DIR
        trace_log(
            frame_counter,
            "force_action",
            string.format("move=%d fire=%d", move_cmd, fire_cmd)
        )
    end

    local start_cmd, coin_cmd = determine_meta_commands(frame_counter, player_alive)
    local ok_apply, apply_err = pcall(controls.apply_action, controls, move_cmd, fire_cmd, start_cmd, coin_cmd)
    if not ok_apply then
        trace_log(frame_counter, "apply_action_error", tostring(apply_err), true)
        return true
    end
    trace_log(
        frame_counter,
        "apply_action",
        string.format("move=%d fire=%d start=%d coin=%d socket_ok=%s", move_cmd, fire_cmd, start_cmd, coin_cmd, tostring(socket_ok))
    )

    previous_player_alive = player_alive
    previous_score = score
    trace_log(frame_counter, "frame_end", "done=" .. tostring(done))
    frame_counter = frame_counter + 1

    return true
end

local function on_mame_exit()
    shutdown_requested = true
    trace_log(frame_counter, "session_stop", "machine stop notifier", true)
    close_socket()
    print("Robotron AI Lua script shutting down.")
end

math.randomseed(os.time())

if not initialize_mame_interface() then
    return
end

print("Robotron socket target: " .. SOCKET_ADDRESS)
controls = Controls:new(manager)
open_socket()

trace_log(nil, "session_start", "robotron lua init", true)
last_save_time = os.time()
previous_player_alive = (read_player_alive(mem) ~= 0) and 1 or 0
previous_score = math.max(0, math.floor(read_player_score(mem) or 0))

global_callback_ref = emu.add_machine_frame_notifier(frame_callback)
emu.add_machine_stop_notifier(on_mame_exit)

print("Robotron AI Lua script initialized.")
