--[[
    Robotron AI Lua script for MAME (baseline bring-up).

    Current scope:
      - Sends a minimal 2-value state vector: [PlayerAlive, Score]
      - Receives dual 8-way joystick commands: movement_dir, firing_dir
      - Uses dummy/startup-safe placeholders where Robotron wiring is still unknown
--]]

local RAW_SOCKET_ADDRESS = os.getenv("ROBOTRON_SOCKET_ADDRESS") or "127.0.0.1:9999"
local SOCKET_ADDRESS = RAW_SOCKET_ADDRESS
if string.sub(SOCKET_ADDRESS, 1, 7) ~= "socket." then
    SOCKET_ADDRESS = "socket." .. SOCKET_ADDRESS
end
local SOCKET_READ_TIMEOUT_S = 3.5
local CONNECTION_RETRY_INTERVAL_S = 1.0
local SAVE_INTERVAL_S = 300
local unpack = table.unpack or unpack

-- Startup diagnostics (bounded, opt-in style flags kept local to script).
local DEBUG_STARTUP_TRACE = true
local DEBUG_TRACE_FRAMES = 10
local DEBUG_BYPASS_SOCKET_FOR_FRAMES = 0
local DEBUG_TRACE_FILE = "logs/startup_trace.log"

local mainCpu = nil
local mem = nil
local controls = nil

local current_socket = nil
local last_connection_attempt_time = 0
local shutdown_requested = false

local frame_counter = 0
local last_save_time = 0
local previous_player_alive = 1
local previous_score = 0

-- Autoboot input sequence (MAME input level, no game-specific memory logic required).
-- Every cycle: pulse Coin 1, then pulse 1P Start shortly after.
local AUTOBOOT_ENABLED = true
local AUTOBOOT_CYCLE_FRAMES = 300
local AUTOBOOT_COIN_PULSE_FRAMES = 3
local AUTOBOOT_START_DELAY_FRAMES = 18
local AUTOBOOT_START_PULSE_FRAMES = 3

-- Robotron RAM symbols (from Williams map):
-- STATUS = 0x9859
-- In PLAYRV, bit0 gates player control update; on player death PLEND sets STATUS to 0x1B.
local STATUS_ADDR = 0x9859
local STATUS_PLAYER_INACTIVE_MASK = 0x01

-- Player PLDATA symbols (from Williams map generated by lwasm):
--   ZP1SCR = 0xBDE4 (4 bytes packed BCD, MSB first)
--   ZP1RP  = 0xBDE8 (4 bytes packed BCD, MSB first)
--   ZP1LAS = 0xBDEC (1 byte)
--   ZP1WAV = 0xBDED (1 byte)
--   ZP1ENM = 0xBDEE (50 bytes; first 22 mirror ELIST fields, rest reserved)
local ZP1SCR_ADDR = 0xBDE4
local ZP1RP_ADDR = 0xBDE8
local ZP1LAS_ADDR = 0xBDEC
local ZP1WAV_ADDR = 0xBDED
local ZP1ENM_ADDR = 0xBDEE
local ZP1ENM_SIZE = 50

local function trace_enabled_for_frame(frame_idx)
    if not DEBUG_STARTUP_TRACE then
        return false
    end
    if frame_idx == nil then
        return false
    end
    return frame_idx < DEBUG_TRACE_FRAMES
end

local function trace_log(frame_idx, phase, detail, force)
    local enabled = force or trace_enabled_for_frame(frame_idx)
    if not enabled then
        return
    end
    local ts = os.date("%Y-%m-%d %H:%M:%S")
    local frame_text = (frame_idx == nil) and "-" or tostring(frame_idx)
    local line = string.format("[trace %s] frame=%s phase=%s %s", ts, frame_text, tostring(phase), tostring(detail or ""))
    print(line)

    local fh = io.open(DEBUG_TRACE_FILE, "a")
    if fh then
        fh:write(line .. "\n")
        fh:close()
    end
end

local function read_player_alive(memory)
    local status = memory:read_u8(STATUS_ADDR)
    if (status & STATUS_PLAYER_INACTIVE_MASK) ~= 0 then
        return 0
    end
    return 1
end

local function decode_bcd4(memory, addr)
    local value = 0
    for i = 0, 3 do
        local byte = memory:read_u8(addr + i)
        local hi = (byte >> 4) & 0x0F
        local lo = byte & 0x0F
        if hi > 9 then hi = 9 end
        if lo > 9 then lo = 9 end
        value = (value * 10) + hi
        value = (value * 10) + lo
    end
    return value
end

local function read_player_score(memory)
    return decode_bcd4(memory, ZP1SCR_ADDR)
end

local function read_next_replay_level(memory)
    return decode_bcd4(memory, ZP1RP_ADDR)
end

local function read_num_lasers(memory)
    return memory:read_u8(ZP1LAS_ADDR)
end

local function read_wave_number(memory)
    return memory:read_u8(ZP1WAV_ADDR)
end

local function read_enemy_state(memory)
    local raw = {}
    for i = 0, ZP1ENM_SIZE - 1 do
        raw[i + 1] = memory:read_u8(ZP1ENM_ADDR + i)
    end

    -- ELIST mirror (first 22 bytes) in order from RRF.ASM.
    local enemy_state = {
        raw = raw,
        robspd = raw[1], rmxspd = raw[2], enfnum = raw[3], enstim = raw[4],
        cdptim = raw[5], hlkspd = raw[6], bshtim = raw[7], brnspd = raw[8],
        tnksht = raw[9], shlspd = raw[10], tdptim = raw[11], sqspd = raw[12],
        robcnt = raw[13], pstcnt = raw[14], momcnt = raw[15], dadcnt = raw[16],
        kidcnt = raw[17], hlkcnt = raw[18], brncnt = raw[19], circnt = raw[20],
        sqcnt = raw[21], tnkcnt = raw[22],
    }

    return enemy_state
end

local function initialize_mame_interface()
    local success, err = pcall(function()
        if not manager or not manager.machine then
            error("MAME manager.machine not available")
        end
        mainCpu = manager.machine.devices[":maincpu"]
        if not mainCpu then
            error("Main CPU not found")
        end
        mem = mainCpu.spaces["program"]
        if not mem then
            error("Program memory space not found")
        end
    end)

    if not success then
        print("Error accessing MAME interface: " .. tostring(err))
        return false
    end

    print("MAME interface initialized.")
    return true
end

local function close_socket()
    if current_socket then
        current_socket:close()
        current_socket = nil
    end
end

local function open_socket()
    close_socket()

    local open_result = nil
    local ok, err = pcall(function()
        local sock = emu.file("rw")
        local result = sock:open(SOCKET_ADDRESS)
        if result == nil then
            -- Required 2-byte handshake.
            sock:write(string.pack(">H", 0))
            current_socket = sock
        else
            open_result = tostring(result)
            sock:close()
        end
    end)

    if not ok or not current_socket then
        local reason = tostring(err or open_result or "unknown error")
        trace_log(nil, "socket_open_failed", "addr=" .. SOCKET_ADDRESS .. " reason=" .. reason, true)
        print("Socket open failed: " .. SOCKET_ADDRESS .. " (" .. reason .. ")")
        close_socket()
        return false
    end

    trace_log(nil, "socket_open_ok", "addr=" .. SOCKET_ADDRESS, true)
    print("Socket connection opened to " .. SOCKET_ADDRESS)
    return true
end

local function find_field(ioport, field_name_options)
    local candidate_ports = {
        ":IN0", ":IN1", ":IN2", ":IN3", ":IN4", ":IN5",
        ":P1", ":P1JOY", ":P1BUTTONS", ":JOYSTICK1", ":JOYSTICK2", ":BUTTONSP1"
    }

    for _, port_name in ipairs(candidate_ports) do
        local port = ioport.ports[port_name]
        if port then
            for _, field_name in ipairs(field_name_options) do
                local field = port.fields[field_name]
                if field then
                    return field
                end
            end
        end
    end

    return nil
end

local Controls = {}
Controls.__index = Controls

function Controls:new(mame_manager)
    local self = setmetatable({}, Controls)
    local ioport = mame_manager.machine.ioport

    self.move_up = find_field(ioport, {"P1 Move Up", "P1 Left Up", "P1 Joystick Up"})
    self.move_down = find_field(ioport, {"P1 Move Down", "P1 Left Down", "P1 Joystick Down"})
    self.move_left = find_field(ioport, {"P1 Move Left", "P1 Left Left", "P1 Joystick Left"})
    self.move_right = find_field(ioport, {"P1 Move Right", "P1 Left Right", "P1 Joystick Right"})

    self.fire_up = find_field(ioport, {"P1 Fire Up", "P1 Right Up"})
    self.fire_down = find_field(ioport, {"P1 Fire Down", "P1 Right Down"})
    self.fire_left = find_field(ioport, {"P1 Fire Left", "P1 Right Left"})
    self.fire_right = find_field(ioport, {"P1 Fire Right", "P1 Right Right"})

    self.p1_start = find_field(ioport, {"1 Player Start", "P1 Start", "Start 1"})
    self.coin_1 = find_field(ioport, {"Coin 1", "P1 Coin", "Insert Coin"})

    if not self.p1_start then
        print("TODO: Robotron start input field not mapped yet (need exact MAME field name).")
    end
    if not self.coin_1 then
        print("TODO: Robotron coin input field not mapped yet (need exact MAME field name).")
    end

    return self
end

local DIR_AXES = {
    [0] = {1, 0, 0, 0}, -- up
    [1] = {1, 0, 0, 1}, -- up-right
    [2] = {0, 0, 0, 1}, -- right
    [3] = {0, 1, 0, 1}, -- down-right
    [4] = {0, 1, 0, 0}, -- down
    [5] = {0, 1, 1, 0}, -- down-left
    [6] = {0, 0, 1, 0}, -- left
    [7] = {1, 0, 1, 0}, -- up-left
}

local function apply_direction(up_field, down_field, left_field, right_field, dir_idx)
    local axis = DIR_AXES[math.max(0, math.min(7, dir_idx or 0))] or DIR_AXES[0]

    if up_field then up_field:set_value(axis[1]) end
    if down_field then down_field:set_value(axis[2]) end
    if left_field then left_field:set_value(axis[3]) end
    if right_field then right_field:set_value(axis[4]) end
end

function Controls:apply_action(move_dir, fire_dir, start_cmd, coin_cmd)
    apply_direction(self.move_up, self.move_down, self.move_left, self.move_right, move_dir)
    apply_direction(self.fire_up, self.fire_down, self.fire_left, self.fire_right, fire_dir)

    if self.p1_start then
        self.p1_start:set_value(start_cmd)
    end
    if self.coin_1 then
        self.coin_1:set_value(coin_cmd)
    end
end

local function serialize_frame(player_alive, score, replay_level, num_lasers, wave_number, enemy_state,
                               done, subj_reward, obj_reward, save_signal)
    local score_u32 = math.max(0, math.min(4294967295, math.floor(score or 0)))
    local replay_u32 = math.max(0, math.min(4294967295, math.floor(replay_level or 0)))
    local lasers_u8 = math.max(0, math.min(255, math.floor(num_lasers or 0)))
    local wave_u8 = math.max(0, math.min(255, math.floor(wave_number or 0)))

    local state_values = {}
    state_values[#state_values + 1] = ((player_alive or 0) ~= 0) and 1.0 or 0.0
    state_values[#state_values + 1] = score_u32 / 99999999.0
    state_values[#state_values + 1] = replay_u32 / 99999999.0
    state_values[#state_values + 1] = lasers_u8 / 9.0
    state_values[#state_values + 1] = wave_u8 / 255.0
    for i = 1, ZP1ENM_SIZE do
        state_values[#state_values + 1] = (enemy_state.raw[i] or 0) / 255.0
    end
    local num_values = #state_values

    local header = string.pack(
        ">HddBIBBIBB",
        num_values,
        subj_reward,
        obj_reward,
        done and 1 or 0,
        score_u32,
        player_alive,
        save_signal,
        replay_u32,
        lasers_u8,
        wave_u8
    )

    local state_payload_parts = {}
    for i = 1, num_values do
        state_payload_parts[#state_payload_parts + 1] = string.pack(">f", state_values[i])
    end
    local state_payload = table.concat(state_payload_parts)
    return header .. state_payload
end

local function process_frame_via_socket(frame_payload, frame_idx)
    if not current_socket then
        trace_log(frame_idx, "socket_open_needed", "no active socket")
        if not open_socket() then
            trace_log(frame_idx, "socket_open_failed", "open_socket() returned false")
            return 0, 0, false
        end
        trace_log(frame_idx, "socket_open_ok", "socket ready")
    end

    local write_ok, write_err = pcall(function()
        trace_log(frame_idx, "socket_write_begin", "payload_bytes=" .. tostring(#frame_payload))
        local length_header = string.pack(">H", #frame_payload)
        current_socket:write(length_header .. frame_payload)
    end)

    if not write_ok then
        trace_log(frame_idx, "socket_write_error", tostring(write_err))
        print("Socket write error: " .. tostring(write_err))
        close_socket()
        return 0, 0, false
    end
    trace_log(frame_idx, "socket_write_ok", "payload sent")

    local read_ok, read_result = pcall(function()
        trace_log(frame_idx, "socket_read_begin", "waiting for 2-byte action")
        local started = os.clock()
        while (os.clock() - started) < SOCKET_READ_TIMEOUT_S do
            local action_bytes = current_socket:read(2)
            if action_bytes and #action_bytes == 2 then
                local move_dir, fire_dir = string.unpack("bb", action_bytes)
                trace_log(frame_idx, "socket_read_ok", string.format("move=%d fire=%d", move_dir, fire_dir))
                return {move_dir, fire_dir}
            end
        end
        trace_log(frame_idx, "socket_read_timeout", "using neutral action")
        return {0, 0}
    end)

    if not read_ok then
        trace_log(frame_idx, "socket_read_error", tostring(read_result))
        print("Socket read error: " .. tostring(read_result))
        close_socket()
        return 0, 0, false
    end

    local move_dir, fire_dir = unpack(read_result)
    return move_dir or 0, fire_dir or 0, true
end

local function determine_meta_commands(frame_idx)
    local start_cmd = 0
    local coin_cmd = 0

    if AUTOBOOT_ENABLED then
        local cycle_pos = frame_idx % AUTOBOOT_CYCLE_FRAMES
        if cycle_pos < AUTOBOOT_COIN_PULSE_FRAMES then
            coin_cmd = 1
        end
        if cycle_pos >= AUTOBOOT_START_DELAY_FRAMES and
           cycle_pos < (AUTOBOOT_START_DELAY_FRAMES + AUTOBOOT_START_PULSE_FRAMES) then
            start_cmd = 1
        end
    end

    return start_cmd, coin_cmd
end

local function frame_callback()
    if not mem or not controls then
        return true
    end

    trace_log(frame_counter, "frame_begin", "callback entered")

    local ok_alive, alive_or_err = pcall(read_player_alive, mem)
    if not ok_alive then
        trace_log(frame_counter, "read_player_alive_error", tostring(alive_or_err), true)
        return true
    end
    local player_alive = (alive_or_err ~= 0) and 1 or 0
    trace_log(frame_counter, "read_player_alive", "alive=" .. tostring(player_alive))

    local ok_core, score, replay_level, num_lasers, wave_number = pcall(function()
        local score = math.max(0, math.floor(read_player_score(mem) or 0))
        local replay_level = math.max(0, math.floor(read_next_replay_level(mem) or 0))
        local num_lasers = math.max(0, math.floor(read_num_lasers(mem) or 0))
        local wave_number = math.max(0, math.floor(read_wave_number(mem) or 0))
        return score, replay_level, num_lasers, wave_number
    end)
    if not ok_core then
        trace_log(frame_counter, "read_core_stats_error", tostring(score), true)
        return true
    end
    trace_log(
        frame_counter,
        "read_core_stats",
        string.format("score=%d replay=%d lasers=%d wave=%d", score, replay_level, num_lasers, wave_number)
    )

    local ok_enemy, enemy_or_err = pcall(read_enemy_state, mem)
    if not ok_enemy then
        trace_log(frame_counter, "read_enemy_state_error", tostring(enemy_or_err), true)
        return true
    end
    local enemy_state = enemy_or_err
    trace_log(frame_counter, "read_enemy_state", "bytes=" .. tostring(#enemy_state.raw))

    local done = (previous_player_alive == 1 and player_alive == 0)
    local obj_reward = score - previous_score
    local subj_reward = 0.0

    local now = os.time()
    local save_signal = 0
    if shutdown_requested or (now - last_save_time) >= SAVE_INTERVAL_S then
        save_signal = 1
        last_save_time = now
    end

    local ok_payload, payload_or_err = pcall(
        serialize_frame,
        player_alive, score, replay_level, num_lasers, wave_number, enemy_state,
        done, subj_reward, obj_reward, save_signal
    )
    if not ok_payload then
        trace_log(frame_counter, "serialize_frame_error", tostring(payload_or_err), true)
        return true
    end
    local payload = payload_or_err
    local payload_count = 5 + ZP1ENM_SIZE
    trace_log(frame_counter, "serialize_frame", "num_values=" .. tostring(payload_count) .. " bytes=" .. tostring(#payload))

    local move_cmd, fire_cmd = 0, 0
    local socket_ok = false
    if DEBUG_BYPASS_SOCKET_FOR_FRAMES > 0 and frame_counter < DEBUG_BYPASS_SOCKET_FOR_FRAMES then
        trace_log(frame_counter, "socket_bypass", "bypassing exchange; neutral action")
        move_cmd, fire_cmd, socket_ok = 0, 0, true
    elseif current_socket then
        move_cmd, fire_cmd, socket_ok = process_frame_via_socket(payload, frame_counter)
    else
        if (now - last_connection_attempt_time) >= CONNECTION_RETRY_INTERVAL_S then
            trace_log(frame_counter, "socket_retry", "attempting reconnect")
            last_connection_attempt_time = now
            open_socket()
        end
        move_cmd, fire_cmd = 0, 0
    end

    if not socket_ok then
        move_cmd, fire_cmd = 0, 0
    end

    local start_cmd, coin_cmd = determine_meta_commands(frame_counter)
    local ok_apply, apply_err = pcall(controls.apply_action, controls, move_cmd, fire_cmd, start_cmd, coin_cmd)
    if not ok_apply then
        trace_log(frame_counter, "apply_action_error", tostring(apply_err), true)
        return true
    end
    trace_log(
        frame_counter,
        "apply_action",
        string.format("move=%d fire=%d start=%d coin=%d socket_ok=%s", move_cmd, fire_cmd, start_cmd, coin_cmd, tostring(socket_ok))
    )

    previous_player_alive = player_alive
    previous_score = score
    trace_log(frame_counter, "frame_end", "done=" .. tostring(done))
    frame_counter = frame_counter + 1

    return true
end

local function on_mame_exit()
    shutdown_requested = true
    trace_log(frame_counter, "session_stop", "machine stop notifier", true)
    close_socket()
    print("Robotron AI Lua script shutting down.")
end

math.randomseed(os.time())

if not initialize_mame_interface() then
    return
end

print("Robotron socket target: " .. SOCKET_ADDRESS)
controls = Controls:new(manager)
open_socket()

trace_log(nil, "session_start", "robotron lua init", true)
last_save_time = os.time()
previous_player_alive = (read_player_alive(mem) ~= 0) and 1 or 0
previous_score = math.max(0, math.floor(read_player_score(mem) or 0))

global_callback_ref = emu.add_machine_frame_notifier(frame_callback)
emu.add_machine_stop_notifier(on_mame_exit)

print("Robotron AI Lua script initialized.")
